// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9bsR8ygqweq6TgWKUoYiSIXF__lVwXj8',
    appId: '1:807722126693:web:f8d212cc1880cf676a258c',
    messagingSenderId: '807722126693',
    projectId: 'gringotts-wallet',
    authDomain: 'gringotts-wallet.firebaseapp.com',
    storageBucket: 'gringotts-wallet.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZNx3gyI1ElUiJdXC3HZkNG1_RVUXT1Gw',
    appId: '1:807722126693:android:baebc37ce7797e6f6a258c',
    messagingSenderId: '807722126693',
    projectId: 'gringotts-wallet',
    storageBucket: 'gringotts-wallet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWUPSXkMtVwM8kYuTGzqhtc8Q1xw4uymo',
    appId: '1:807722126693:ios:9fb8c0bef867aa556a258c',
    messagingSenderId: '807722126693',
    projectId: 'gringotts-wallet',
    storageBucket: 'gringotts-wallet.firebasestorage.app',
    iosBundleId: 'com.example.stellarWalletApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWUPSXkMtVwM8kYuTGzqhtc8Q1xw4uymo',
    appId: '1:807722126693:ios:9fb8c0bef867aa556a258c',
    messagingSenderId: '807722126693',
    projectId: 'gringotts-wallet',
    storageBucket: 'gringotts-wallet.firebasestorage.app',
    iosBundleId: 'com.example.stellarWalletApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9bsR8ygqweq6TgWKUoYiSIXF__lVwXj8',
    appId: '1:807722126693:web:1a77cde4d3d956896a258c',
    messagingSenderId: '807722126693',
    projectId: 'gringotts-wallet',
    authDomain: 'gringotts-wallet.firebaseapp.com',
    storageBucket: 'gringotts-wallet.firebasestorage.app',
  );
}
